import StyledJsxRegistry from '@/lib/styled-jsx-registry';
import type { Metadata } from 'next';
import ThemeSwitcher from '../components/theme-switcher';
import { ThemeContextProvider } from '../contexts/theme-context';
import { Body, GlobalStyles } from './styles/globals';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <ThemeContextProvider>
        <StyledJsxRegistry>
          <GlobalStyles />
          <Body>
            {children}
            <ThemeSwitcher />
          </Body>
        </StyledJsxRegistry>
      </ThemeContextProvider>
    </html>
  );
}
